// =====================================================================
// RENTBOOK KENYA — BULK RENAME MODAL
// Re-applies a naming scheme with before & after comparison table
// Supports Kenyan ground floor conventions ('G', 'Ground', 'GF') and inline editing
// =====================================================================

import React, { useMemo, useState } from 'react';
import { ArrowRight, Check, Edit2, RotateCcw, Sparkles, X } from 'lucide-react';
import { Modal } from '../common/Modal';
import { useApp } from '../../context/AppContext';
import { GroundFloorNaming, NamingSchemeConfig, NamingSchemeType } from '../../types';
import { generateUnitNames, getFloorDisplayName } from '../../lib/namingEngine';

export const BulkRenameModal: React.FC = () => {
  const {
    isBulkRenameModalOpen,
    closeBulkRenameModal,
    bulkRenamePropertyId,
    properties,
    units,
    bulkRenameUnits,
  } = useApp();

  const property = properties.find((p) => p.id === bulkRenamePropertyId);
  const propertyUnits = units.filter(
    (u) => u.property_id === bulkRenamePropertyId && !u.deleted_at
  );

  const [schemeType, setSchemeType] = useState<NamingSchemeType>('scheme1');
  const [groundFloorNaming, setGroundFloorNaming] = useState<GroundFloorNaming>('G');
  const [prefixWord, setPrefixWord] = useState<'House' | 'Unit' | 'Door'>('House');
  const [customPattern, setCustomPattern] = useState('{block}{floor}{index}');
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Manual tweaks map: unitId -> custom new name
  const [customNamesMap, setCustomNamesMap] = useState<Record<string, string>>({});
  const [editingUnitId, setEditingUnitId] = useState<string | null>(null);
  const [editingValue, setEditingValue] = useState('');

  const schemeConfig = useMemo<NamingSchemeConfig>(() => {
    return {
      type: schemeType,
      prefixWord,
      customPattern,
      groundFloorNaming,
    };
  }, [schemeType, prefixWord, customPattern, groundFloorNaming]);

  const autoGeneratedNames = useMemo(() => {
    if (!property) return [];
    return generateUnitNames(
      property.floors,
      property.units_per_floor,
      schemeConfig,
      property.blocks
    );
  }, [property, schemeConfig]);

  if (!property) return null;

  const handleStartEdit = (unitId: string, currentVal: string) => {
    setEditingUnitId(unitId);
    setEditingValue(currentVal);
  };

  const handleSaveEdit = (unitId: string) => {
    if (!editingValue.trim()) return;
    setCustomNamesMap((prev) => ({
      ...prev,
      [unitId]: editingValue.trim(),
    }));
    setEditingUnitId(null);
  };

  const handleResetCustoms = () => {
    setCustomNamesMap({});
    setEditingUnitId(null);
  };

  const handleApply = async () => {
    const customCount = Object.keys(customNamesMap).length;
    const message = customCount > 0
      ? `Apply bulk rename across all ${propertyUnits.length} units in ${property.name} (including ${customCount} manual edits)?`
      : `Apply bulk rename across all ${propertyUnits.length} units in ${property.name}?`;

    const confirmed = window.confirm(message);
    if (!confirmed) return;

    setIsSubmitting(true);
    try {
      await bulkRenameUnits(property.id, schemeConfig, customNamesMap);
      closeBulkRenameModal();
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Modal
      isOpen={isBulkRenameModalOpen}
      onClose={closeBulkRenameModal}
      title={`Bulk Rename Houses — ${property.name}`}
      subtitle="Re-apply naming scheme with Kenyan ground floor ('G' / 'Ground') conventions and live edits"
      maxWidth="lg"
    >
      <div className="flex flex-col gap-4 text-xs">
        {/* Kenyan Ground Floor Convention Selector */}
        <div className="bg-slate-900/90 border border-emerald-500/40 p-2.5">
          <label className="block text-slate-300 font-semibold mb-1 flex items-center justify-between text-xs">
            <span className="flex items-center gap-1.5">
              <span className="w-2 h-2 rounded-full bg-emerald-400"></span>
              <span>Ground Floor Unit Naming (Kenyan Standard)</span>
            </span>
            <span className="text-[10px] text-emerald-400 font-mono">
              Kenyan flats use "G" or "Ground"
            </span>
          </label>
          <div className="grid grid-cols-4 gap-1.5">
            {[
              { id: 'G' as const, label: '“G” Prefix', example: 'G1, G2, G3...' },
              { id: 'Ground' as const, label: '“Ground” Name', example: 'Ground 1, Ground 2...' },
              { id: 'GF' as const, label: '“GF” Prefix', example: 'GF1, GF2, GF3...' },
              { id: 'Letter' as const, label: 'Letter “A”', example: 'A1, A2, A3...' },
            ].map((opt) => (
              <button
                key={opt.id}
                type="button"
                onClick={() => setGroundFloorNaming(opt.id)}
                className={`p-2 text-left border transition ${
                  groundFloorNaming === opt.id
                    ? 'bg-emerald-950/70 border-emerald-500 text-emerald-200 ring-1 ring-emerald-500'
                    : 'bg-slate-800/70 border-slate-700/80 text-slate-300 hover:bg-slate-800'
                }`}
              >
                <div className="font-bold text-[11px]">{opt.label}</div>
                <div className="text-[10px] font-mono text-emerald-400 truncate">{opt.example}</div>
              </button>
            ))}
          </div>
        </div>

        {/* Scheme Picker */}
        <div>
          <label className="block text-slate-300 font-semibold mb-1 flex items-center gap-1.5">
            <Sparkles className="w-3.5 h-3.5 text-amber-400" />
            <span>Select Target Naming Scheme</span>
          </label>
          <select
            value={schemeType}
            onChange={(e) => setSchemeType(e.target.value as NamingSchemeType)}
            className="w-full bg-slate-800 border border-slate-700 px-3 py-2 text-xs text-slate-100 min-h-[40px]"
          >
            <option value="scheme1">
              Scheme 1: Block + Unit (Ground={groundFloorNaming === 'Ground' ? 'Ground 1..4' : 'G1..G4'}, 1st=A1..A4)
            </option>
            <option value="scheme2">
              Scheme 2: Floor Prefix + Number ({groundFloorNaming === 'Ground' ? 'Ground 1..4' : 'G1..G4'}, F1..F4, S1..S4)
            </option>
            <option value="scheme3">Scheme 3: Simple Sequential (1, 2, 3, 4, 5...)</option>
            <option value="scheme4">Scheme 4: Floor Number + Letter (GA..GD, 1A..1D...)</option>
            <option value="scheme5">Scheme 5: Word Prefix (House 1, House 2...)</option>
            <option value="scheme6">Scheme 6: Custom Token Pattern</option>
          </select>
        </div>

        {/* Side-by-Side Comparison Table with Inline Editing */}
        <div className="flex flex-col gap-1.5">
          <div className="flex items-center justify-between text-slate-400 text-[11px]">
            <span>Click any new name or the pencil icon to tweak before applying</span>
            {Object.keys(customNamesMap).length > 0 && (
              <button
                type="button"
                onClick={handleResetCustoms}
                className="text-amber-400 hover:underline flex items-center gap-1"
              >
                <RotateCcw className="w-3 h-3" />
                <span>Reset {Object.keys(customNamesMap).length} manual edits</span>
              </button>
            )}
          </div>

          <div className="border border-slate-700/80 overflow-hidden bg-slate-950/60 max-h-64 overflow-y-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-slate-800/80 text-slate-300 border-b border-slate-700 sticky top-0">
                <tr>
                  <th className="px-3 py-2 font-semibold">Current Name</th>
                  <th className="px-2 py-2 font-semibold text-slate-400">Floor</th>
                  <th className="px-2 py-2 text-center w-8"></th>
                  <th className="px-3 py-2 font-semibold text-emerald-400">Proposed New Name</th>
                  <th className="px-2 py-2 text-right w-12">Edit</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-800">
                {propertyUnits.map((u, i) => {
                  const autoName = autoGeneratedNames[i]?.name || u.name;
                  const finalName = customNamesMap[u.id] || autoName;
                  const isCustom = Boolean(customNamesMap[u.id]);
                  const isEditing = editingUnitId === u.id;

                  return (
                    <tr key={u.id} className="hover:bg-slate-800/40">
                      <td className="px-3 py-2 font-mono text-slate-300">{u.name}</td>
                      <td className="px-2 py-2 text-[11px] text-slate-400">
                        {getFloorDisplayName(u.floor_number)}
                      </td>
                      <td className="px-2 py-2 text-center text-slate-500">
                        <ArrowRight className="w-3.5 h-3.5 inline" />
                      </td>
                      <td className="px-3 py-2">
                        {isEditing ? (
                          <div className="flex items-center gap-1">
                            <input
                              type="text"
                              value={editingValue}
                              onChange={(e) => setEditingValue(e.target.value)}
                              onKeyDown={(e) => {
                                if (e.key === 'Enter') handleSaveEdit(u.id);
                                if (e.key === 'Escape') setEditingUnitId(null);
                              }}
                              className="px-2 py-1 bg-slate-800 border border-emerald-500 font-mono font-bold text-emerald-300 text-xs w-28 focus:outline-none"
                              autoFocus
                            />
                            <button
                              type="button"
                              onClick={() => handleSaveEdit(u.id)}
                              className="p-1 text-emerald-400 hover:text-emerald-300"
                            >
                              <Check className="w-3.5 h-3.5" />
                            </button>
                            <button
                              type="button"
                              onClick={() => setEditingUnitId(null)}
                              className="p-1 text-slate-400 hover:text-rose-400"
                            >
                              <X className="w-3.5 h-3.5" />
                            </button>
                          </div>
                        ) : (
                          <span
                            onClick={() => handleStartEdit(u.id, finalName)}
                            className={`font-mono font-bold cursor-pointer hover:underline flex items-center gap-1.5 ${
                              isCustom ? 'text-amber-400' : 'text-emerald-400'
                            }`}
                            title="Click to rename"
                          >
                            <span>{finalName}</span>
                            {isCustom && (
                              <span className="text-[9px] px-1 bg-amber-500/20 text-amber-300 font-semibold rounded">
                                Edited
                              </span>
                            )}
                          </span>
                        )}
                      </td>
                      <td className="px-2 py-2 text-right">
                        {!isEditing && (
                          <button
                            type="button"
                            onClick={() => handleStartEdit(u.id, finalName)}
                            className="p-1 text-slate-400 hover:text-emerald-400 rounded"
                            title="Edit new name"
                          >
                            <Edit2 className="w-3 h-3" />
                          </button>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>

        {/* Warning Callout */}
        <div className="bg-amber-950/40 border border-amber-600/40 p-2.5 text-[11px] text-amber-200">
          <strong>Note:</strong> Bulk rename applies the selected naming convention across all flats.
          Tenants, balances, and payment records remain intact and linked.
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-800">
          <button
            type="button"
            onClick={closeBulkRenameModal}
            className="px-4 py-2.5 text-slate-300 hover:bg-slate-800 font-medium transition min-h-[44px]"
          >
            Cancel
          </button>
          <button
            type="button"
            onClick={handleApply}
            disabled={isSubmitting}
            className="px-6 py-2.5 bg-emerald-600 hover:bg-emerald-500 text-white font-bold shadow-md hover:shadow-lg transition active:scale-95 disabled:opacity-50 min-h-[44px]"
          >
            {isSubmitting ? 'Applying...' : 'Apply Bulk Rename'}
          </button>
        </div>
      </div>
    </Modal>
  );
};
